/* Phase12.5 mode boundaries. Fixtures specified independently from retained feature harnesses;
 * game-rule arithmetic remains covered by those suites. Real clicks, keyboard, DOM and saved data
 * are the oracles; no assertion compares selector strings with their implementation. */
'use strict';
const {chromium}=require('playwright'),{pathToFileURL}=require('url'),path=require('path');
const SHEET=path.resolve(process.argv[2]||path.join(__dirname,'../../Part F — Cross-Platform Delivery/PART F — Phase 0 Source Reorganization for Maintainability/l5r-character-sheet.html'));
let passed=0,failed=0;const contexts=[];
function check(id,a,e=true){if(JSON.stringify(a)===JSON.stringify(e)){passed++;console.log('PASS '+id);}else{failed++;console.log('FAIL '+id+'\n expected '+JSON.stringify(e)+'\n actual '+JSON.stringify(a));}}
async function scenario(id,fn){try{await fn();}catch(e){check('PM125-SCENARIO-'+id,String(e.message).split('\n')[0],'completed');}}
const F=(name,config,side='adv')=>({name,config,side,cost:'5',desc:'Fixture description'});
// Every configurable UI/schema family, including renderers with special inline controls.
const FIXTURES=[
 F('Elemental Blessing',{type:'ringPick',value:'Fire'}),F('Gentry',{type:'severityTier',value:'Village'}),
 F('Allies',{type:'dualTierPick',influence:1,devotion:2}),F('Luck',{type:'rankPick',rank:2,value:'Rank 2',remaining:1}),
 F('Kharmic Tie',{type:'rankPick',rank:2,value:'Rank 2',target:'Akiko',remaining:1,sourceId:'pm125-tie'}),
 F('Languages',{type:'languagePick',languageType:'Human',language:'Senpet',value:'Human'}),
 F('Magic Resistance',{type:'rankPick',rank:2,value:'Rank 2'}),F('Great Potential',{type:'skillPick',skill:'Courtier',value:'Courtier'}),
 F('Sacred Weapon',{type:'clanWeaponAutoPick',clan:'Phoenix',value:'inquisitors-strike',sourceId:'pm125-sacred'}),
 F('Wealthy',{type:'rankFreePick',rank:2,value:'Rank 2'}),
 F('Blackmail',{type:'targetStatusPick',revision:1,target:'Akiko',targetStatus:3}),
 F('Forbidden Knowledge',{type:'knowledgePick',revision:1,subject:'Kolat',notes:'Manually managed'}),
 F('Inheritance',{type:'itemPick',revision:1,itemName:'Family fan'}),F('Way of the Land',{type:'regionPick',revision:1,region:'Naishou'}),
 F('Darling of the Court',{type:'courtList',revision:1,courts:['Winter Court','Imperial Court'],selected:'Winter Court',inSession:false,value:'Winter Court, Imperial Court'}),
 F('Heart of Vengeance',{type:'factionPick',revision:1,faction:'Scorpion Clan',value:'Scorpion Clan'}),
 F('Paragon',{type:'paragonTenet',revision:1,tenet:'Courage',value:'Courage'}),
 F('Soul of Artistry',{type:'skillFamilyPick',revision:1,family:'Artisan',value:'Artisan'}),
 F('Void Versatility',{type:'voidVersatilityRing',revision:1,ring:'Air',value:'Air'}),
 F('Seven Fortunes’ Blessing',{type:'fortuneBlessing',revision:1,fortune:'Hotei',value:'Hotei'}),
 F('Dark Paragon',{type:'darkParagon',revision:1,precept:'Will',value:'Will',remaining:1}),
 F('Touch of the Spirit Realms',{type:'spiritRealmTouch',revision:1,realm:'Jigoku',value:'Jigoku',lost:false}),
 F('Antisocial',{type:'tierPick',tier:2,value:'2'},'disadv'),F('Blackmailed',{type:'statusLinked',value:'Status'},'disadv'),
 F('Consumed',{type:'tenetPick',tenet:'Control',value:'Control'},'disadv'),F('Elemental Imbalance',{type:'elementPick',rank:1,element:'Air',value:'Air'},'disadv'),
 F('Enlightened Madness',{type:'targetPick',tier:4,targetType:'Tattoo',target:'Dragon',value:'Dragon'},'disadv'),
 F('Phobia',{type:'toggleModifier',rank:2,active:false},'disadv'),
 F('Sworn Enemy',{type:'insightDifferencePick',target:'Bayushi',difference:1,nemesis:true,active:false},'disadv'),
 F('Unlucky',{type:'rankPick',rank:2,remaining:1,value:'Rank 2'},'disadv'),
 F('Dependant',{type:'rankPick',points:3,dependant:'Akiko',arrangement:'Support at court',value:'3 points'},'disadv'),
 F('Doubt',{type:'skillPick',skill:'Courtier',value:'Courtier'},'disadv'),
 F('Cursed by the Realm',{type:'realmPick',realm:'Tengoku',inTemple:false,value:'Tengoku'},'disadv'),
 F('Seven Fortunes’ Curse',{type:'fortunePick',fortune:'Ebisu',active:false,value:'Ebisu'},'disadv'),
 F('Wrath of the Kami',{type:'elementPick',element:'Fire',value:'Fire'},'disadv')];
const slug=s=>s.toUpperCase().replace(/[^A-Z0-9]+/g,'-').replace(/-$/,'');
async function fresh(browser){const c=await browser.newContext({viewport:{width:390,height:844}});contexts.push(c);const p=await c.newPage();p.setDefaultTimeout(2000);p.errors=[];p.on('pageerror',e=>p.errors.push(String(e)));await p.route('https://fonts.googleapis.com/**',r=>r.abort());await p.route('https://fonts.gstatic.com/**',r=>r.abort());await p.goto(pathToFileURL(SHEET).href,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__L5R_TEST__?.CL11?.ready);return p;}
const mode=(p,m)=>p.evaluate(m=>window.__L5R_TEST__.MODES12?.set(m),m);
async function seed(p,fixtures=FIXTURES){await p.evaluate(fixtures=>{const T=window.__L5R_TEST__;T.closeAdvConfigModal();T.resetToBaseline();T.saveSchoolsList([{name:'Isawa Shugenja',frozen:false,frozenRank:null,floorRank:1,anchorInsightRank:0}]);document.getElementById('f_schoolAffinity').value='Void';document.getElementById('f_clan').value='Phoenix';document.getElementById('f_taint').value='1';T.recalcAll();const d=T.collectData();d.adv=fixtures.filter(x=>x.side==='adv').map(({side,...x})=>x);d.disadv=fixtures.filter(x=>x.side==='disadv').map(({side,...x})=>x);d.fields.f_honorPts='5.0';d.fields.f_statusRank='3';T.applyData(d);T.recalcAll();},fixtures);await p.waitForTimeout(40);}
const data=p=>p.evaluate(()=>JSON.stringify(window.__L5R_TEST__.collectData()));
async function row(p,f){return p.evaluate(f=>{const a=[...document.querySelectorAll('#'+f.side+'List .entry')];const i=a.findIndex(e=>e.querySelector('.en-name').value===f.name);return '#'+f.side+'List .entry:nth-child('+(i+1)+')';},f);}
async function click(p,s){return p.evaluate(s=>{const e=document.querySelector(s==='#advConfigCancel'?'#advConfigX':s);if(!e)return false;e.click();return true;},s);}
async function config(p,name,side='adv'){return p.evaluate(({name,side})=>{const e=[...document.querySelectorAll('#'+side+'List .entry')].find(e=>e.querySelector('.en-name').value===name);return e?.dataset.advConfig?JSON.parse(e.dataset.advConfig):null;},{name,side});}
const shown=p=>p.evaluate(()=>getComputedStyle(document.getElementById('advConfigModalOverlay')).display!=='none');
async function type(p,s,value){await p.evaluate(async s=>{const tab=document.querySelector(s).closest('#techList')?'Techniques':'Adv & Disadv';const C=window.__L5R_CAROUSEL__;C.goToTab(tab);if(C.whenSettled)await C.whenSettled();const e=document.querySelector(s);e.focus();e.setSelectionRange(0,e.value.length);},s);await p.keyboard.type(value);return p.locator(s).first().inputValue();}
async function closeRoll(p){await p.evaluate(()=>{for(const id of ['rollPreviewCancel','rollModalClose','appConfirmCancel','stanceInfoClose'])document.getElementById(id)?.click();});}
async function roll(p){const pending=p.evaluate(()=>{const T=window.__L5R_TEST__;return T.rollWithModifiers('Mode resource test',T.makeRollContext(T.ROLL_KINDS.SKILL,{skillName:'Courtier',traitName:'Awareness',skillRank:2}),4,2).then(Boolean);});pending.catch(()=>{});await p.waitForSelector('#rollPreviewGo',{state:'visible'});await click(p,'#rollPreviewGo');await pending;}
async function main(){const b=await chromium.launch();try{
 if(process.argv.includes('--boundary-probe')){
   const p=await fresh(b);await seed(p,[F('Dependant',{type:'rankPick',points:3,dependant:'Akiko',value:'3 points'},'disadv'),F('Allies',{type:'dualTierPick',influence:1,devotion:2})]);
   await p.evaluate(async()=>{const C=window.__L5R_CAROUSEL__;C.goToTab('Adv & Disadv');await C.whenSettled();});await p.locator('.dep458-input').first().fill('New name');await p.locator('.dep458-input').first().dispatchEvent('change');
   const typed=(await config(p,'Dependant','disadv')).dependant;await mode(p,'play');await click(p,'#advList .adv-config-btn');
   console.log('BOUNDARY '+JSON.stringify({typed,configVisible:await shown(p),rowReadonly:await p.locator('#advList .en-name').evaluate(e=>e.readOnly)}));return;
 }
 await scenario('MATRIX',async()=>{const p=await fresh(b);await seed(p);check('PM125-ENABLED',await p.evaluate(()=>window.__L5R_TEST__.MODES125_ENABLED));
 for(const f of FIXTURES){const s=await row(p,f),id=slug(f.name);check('PM125-FIXTURE-'+id,await p.locator(s+' .adv-config-row.configured').count(),1);const btn=s+' .adv-config-btn:not(.fb4521-hotei-roll)';if(await p.locator(btn).count()){await click(p,btn);check('PM125-MANAGEMENT-'+(f.name==='Sacred Weapon'?'AUTO-':'OPEN-')+id,await shown(p),f.name!=='Sacred Weapon');await click(p,'#advConfigCancel');}}
 const before=await data(p);await mode(p,'play');
 for(const f of FIXTURES){const s=await row(p,f),id=slug(f.name);check('PM125-LOCK-'+id,await p.evaluate(s=>{const e=document.querySelector(s);return ['.en-name','.en-cost','.en-desc'].every(x=>e.querySelector(x).readOnly)&&getComputedStyle(e.querySelector('.rm-btn')).display==='none';},s));const btn=s+' .adv-config-btn:not(.fb4521-hotei-roll)';if(await p.locator(btn).count()){await click(p,btn);check('PM125-PLAY-CONFIG-INERT-'+id,await shown(p),false);}}
 check('PM125-MODE-NO-DATA-OR-XP-CHANGE',await data(p),before);
 check('PM125-PLAY-ADD-HIDDEN',await p.evaluate(()=>['advQuickAdd','disadvQuickAdd','addAdv','addDisadv'].every(id=>getComputedStyle(document.getElementById(id)).display==='none')));
 for(const side of ['adv','disadv']){const count=await p.locator('#'+side+'List .entry').count();await click(p,side==='adv'?'#addAdv':'#addDisadv');check('PM125-ADD-INERT-'+side,await p.locator('#'+side+'List .entry').count(),count);const beforeRemove=await p.locator('#'+side+'List .entry').count();await click(p,'#'+side+'List .entry:last-child .rm-btn');check('PM125-REMOVE-INERT-'+side,await p.locator('#'+side+'List .entry').count(),beforeRemove);}
 const first='#advList .entry:first-child';check('PM125-TYPING-INERT',await type(p,first+' .en-name','changed'),'Elemental Blessing');check('PM125-PLAIN-TEXT-CSS',await p.evaluate(s=>getComputedStyle(document.querySelector(s+' .en-name')).borderTopColor,first),'rgba(0, 0, 0, 0)');
 await mode(p,'management');check('PM125-MANAGEMENT-RESTORED',await type(p,first+' .en-name','Editable'),'Editable');const count=await p.locator('#advList .entry').count();await click(p,'#addAdv');check('PM125-MANAGEMENT-ADD',await p.locator('#advList .entry').count(),count+1);await click(p,'#advList .entry:last-child .rm-btn');check('PM125-MANAGEMENT-REMOVE',await p.locator('#advList .entry').count(),count);check('PM125-MATRIX-NO-ERRORS',p.errors,[]);
 });
 await scenario('BOUNDARIES',async()=>{const p=await fresh(b);await seed(p,[F('Darling of the Court',{type:'courtList',revision:1,courts:['Winter Court'],selected:'Winter Court',inSession:false,value:'Winter Court'}),F('Dependant',{type:'rankPick',points:3,dependant:'Akiko',arrangement:'Support at court',value:'3 points'},'disadv'),F('Wealthy',{type:'rankFreePick',rank:2,value:'Rank 2'})]);const before=await data(p);await click(p,'#advList .adv-config-btn');await p.locator('#advConfigGrid .court4514-input').fill('Draft must disappear');await mode(p,'play');check('PM125-MODAL-CLOSED',await shown(p),false);await mode(p,'management');await click(p,'#advConfigConfirm');check('PM125-DRAFT-CANCELLED-NO-LATE-COMMIT',await data(p),before);await click(p,'#advList .adv-config-btn');check('PM125-DRAFT-DISCARDED-ON-REOPEN',await p.locator('#advConfigGrid .court4514-input').inputValue(),'Winter Court');await click(p,'#advConfigCancel');
 const dep='#disadvList .dep458-input';const old=await p.locator(dep).first().inputValue();await mode(p,'play');check('PM125-DEPENDANT-INLINE-LOCK',await type(p,dep,'changed'),old);check('PM125-DEPENDANT-READONLY',await p.locator(dep).first().evaluate(e=>e.readOnly));await p.evaluate(()=>{const e=document.querySelector('.dep458-input');e.value='Blocked change';e.dispatchEvent(new Event('change',{bubbles:true}));});check('PM125-DEPENDANT-CHANGE-GATE',(await config(p,'Dependant','disadv')).dependant,'Akiko');await p.evaluate(()=>window.__L5R_TEST__.recalcAll());const wealth=await data(p);await click(p,'.wealth4517-btn');check('PM125-WEALTHY-GRANT-INERT',await data(p),wealth);
 // The provider commits on change. Actual typing is separately compared with the pre-phase
 // build by --boundary-probe: a pre-existing document input refresh discards it before blur.
 await mode(p,'management');await p.evaluate(()=>{const e=document.querySelector('.dep458-input');e.value='A new name';e.dispatchEvent(new Event('change',{bubbles:true}));});check('PM125-DEPENDANT-CHANGE-COMMIT-RESTORED',(await config(p,'Dependant','disadv')).dependant,'A new name');
 await click(p,'#advList .adv-config-btn');await p.locator('#advConfigGrid .court4514-input').fill('Autumn Court');await click(p,'#advConfigConfirm');check('PM125-MANAGEMENT-CONFIG-COMMITS',(await config(p,'Darling of the Court')).courts,['Autumn Court']);
 // Capture gate independently of the stale-dialog cancellation and hiding CSS.
 await mode(p,'management');await click(p,'#advList .adv-config-btn');await mode(p,'play');check('PM125-GRID-CONFIRM-EVENT-GATE',await p.evaluate(()=>{let grid=0,confirm=0;const g=document.getElementById('advConfigGrid'),c=document.getElementById('advConfigConfirm');const a=()=>grid++,b=()=>confirm++;g.addEventListener('click',a);c.addEventListener('click',b);g.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true}));c.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true}));g.removeEventListener('click',a);c.removeEventListener('click',b);return [grid,confirm];}),[0,0]);
 await p.evaluate(()=>{const T=window.__L5R_TEST__,d=T.collectData();d.adv.push({name:'Allies',cost:0,desc:'Unconfigured'});T.applyData(d);});await p.waitForTimeout(60);check('PM125-REAL-REBUILD-ALREADY-PLAY',await p.evaluate(()=>{const e=[...document.querySelectorAll('#advList .entry')].find(e=>e.querySelector('.en-name').value==='Allies');return [e.querySelector('.en-name').readOnly,!!e.querySelector('.unconfigured'),e.querySelector('.adv-config-btn').disabled];}),[true,true,true]);
 // Shared class names in another section must not be captured by this part.
 await p.evaluate(()=>{const e=document.createElement('input');e.className='adv-config-btn dep458-input wealth4517-btn';e.id='pm125-isolation';document.getElementById('techList').appendChild(e);});await p.waitForTimeout(30);check('PM125-TECHNIQUE-DOM-ISOLATION',await type(p,'#pm125-isolation','Still editable'),'Still editable');check('PM125-BOUNDARIES-NO-ERRORS',p.errors,[]);
 });
 await scenario('NATURAL-DISABLED',async()=>{const p=await fresh(b);await seed(p,[F('Wealthy',{type:'rankFreePick',rank:1,value:'Rank 1',wealth4517:{revision:1,granted:6}})]);await p.evaluate(()=>{document.getElementById('f_koku').value='0';window.__L5R_TEST__.recalcAll();});check('PM125-WEALTHY-RETURN-STARTS-DISABLED',await p.locator('.wealth4517-btn').first().isDisabled());await mode(p,'play');await mode(p,'management');check('PM125-WEALTHY-NATURAL-DISABLED-PRESERVED',await p.locator('.wealth4517-btn').first().isDisabled());});
 await scenario('PLAY-ACTIONS',async()=>{const p=await fresh(b);await seed(p);await mode(p,'play');
 await p.evaluate(async()=>{const C=window.__L5R_CAROUSEL__;C.goToTab('Adv & Disadv');await C.whenSettled();});
 for(const [id,s] of [['HOTEI','.fb4521-hotei-roll'],['TATTOO','.d45-tattoo-check'],['PHOBIA','.d45-phobia-row .d45-toggle'],['NEMESIS','.d45-nemesis-row .d45-toggle'],['REALM',(await row(p,F('Cursed by the Realm',{},'disadv')))+' .d45-toggle'],['COURT','.court4514-courts input'],['COURT-SESSION','.court4514-session-box'],['LOST','.tr4524-lost input'],['DP-USE','.dp4523-use'],['DP-RESET','.dp4523-reset'],['LUCK-RESET',(await row(p,F('Luck',{})))+' .adv-config-reset-session'],['TIE-RESET',(await row(p,F('Kharmic Tie',{})))+' .adv-config-reset-session'],['UNLUCKY','.unlucky-btn'],['INFO','.fb4521-info']])check('PM125-VISIBLE-PLAY-'+id,await p.locator(s).first().isVisible());
 for(const [name,field] of [['Phobia','active'],['Sworn Enemy','active'],['Cursed by the Realm','inTemple']]){const s=await row(p,F(name,{},'disadv')),toggle=s+' .d45-toggle';await click(p,toggle);check('PM125-PLAY-TOGGLE-'+slug(name),(await config(p,name,'disadv'))?.[field],true);await click(p,toggle);}
 await p.locator('.court4514-courts input').last().evaluate(e=>e.click());check('PM125-COURT-SELECTION',(await config(p,'Darling of the Court')).selected,'Imperial Court');await click(p,'.court4514-session-box');check('PM125-COURT-SESSION',(await config(p,'Darling of the Court')).inSession,true);
 await click(p,'.tr4524-lost input');check('PM125-LOST-TOGGLE',(await config(p,'Touch of the Spirit Realms')).lost,true);
 await click(p,'.fb4521-hotei-roll');check('PM125-HOTEI-ROLL-ACTION',await p.locator('#rollPreviewOverlay').isVisible());await closeRoll(p);
 await click(p,'.d45-tattoo-check');check('PM125-TATTOO-CHECK-ACTION',await p.locator('#rollPreviewOverlay').isVisible()&&/Willpower/.test(await p.locator('#rollPreviewOverlay').textContent()));await closeRoll(p);
 for(const name of ['Luck','Kharmic Tie']){const s=await row(p,F(name,{}));await click(p,s+' .adv-config-reset-session');check('PM125-RESET-'+slug(name),(await config(p,name)).remaining,2);}
 const u=await row(p,F('Unlucky',{},'disadv'));await click(p,u+' .unlucky-btn');check('PM125-UNLUCKY-MINUS',(await config(p,'Unlucky','disadv')).remaining,0);await mode(p,'management');await mode(p,'play');check('PM125-RESOURCE-DISABLED-PRESERVED',await p.locator(u+' .unlucky-btn').first().isDisabled());await p.locator(u+' .unlucky-btn').nth(1).evaluate(e=>e.click());check('PM125-UNLUCKY-PLUS',(await config(p,'Unlucky','disadv')).remaining,1);await p.locator(u+' .unlucky-btn').nth(2).evaluate(e=>e.click());check('PM125-UNLUCKY-RESET',(await config(p,'Unlucky','disadv')).remaining,2);
 await click(p,'.dp4523-use');await click(p,'#appConfirmOk');check('PM125-DARK-PARAGON-USE',(await config(p,'Dark Paragon')).remaining,0);await click(p,'.dp4523-reset');check('PM125-DARK-PARAGON-RESET',(await config(p,'Dark Paragon')).remaining,1);
 check('PM125-INFO-ACTION',await p.evaluate(()=>{const e=document.querySelector('.fb4521-info');if(!e)return false;e.click();const o=document.querySelector('#stanceInfoOverlay');return !!o&&getComputedStyle(o).display!=='none'&&/Hotei/.test(o.textContent);}));await closeRoll(p);check('PM125-PLAY-ACTIONS-NO-ERRORS',p.errors,[]);
 });
 await scenario('REALM-CHECK',async()=>{const p=await fresh(b);await seed(p,[F('Cursed by the Realm',{type:'realmPick',realm:'Toshigoku',value:'Toshigoku'},'disadv')]);await mode(p,'play');await p.evaluate(async()=>{const C=window.__L5R_CAROUSEL__;C.goToTab('Adv & Disadv');await C.whenSettled();});check('PM125-VISIBLE-REALM-CHECK',await p.locator('button.realm4510-check').isVisible());await p.locator('button.realm4510-check').click();check('PM125-REALM-CHECK-ACTION',await p.locator('#rollPreviewOverlay').isVisible()&&/Toshigoku/.test(await p.locator('#rollPreviewOverlay').textContent()));await closeRoll(p);check('PM125-REALM-CHECK-NO-ERRORS',p.errors,[]);});
 await scenario('REROLLS',async()=>{const p=await fresh(b);await seed(p,[F('Luck',{type:'rankPick',rank:1,value:'Rank 1',remaining:1}),F('Dark Paragon',{type:'darkParagon',revision:1,precept:'Control',value:'Control',remaining:1}),F('Unlucky',{type:'rankPick',rank:2,remaining:2,value:'Rank 2'},'disadv')]);await mode(p,'play');await roll(p);check('PM125-VISIBLE-LUCK-REROLL',await p.locator('.adv-config-spend-luck').isVisible());await click(p,'.adv-config-spend-luck');check('PM125-LUCK-REROLL',(await config(p,'Luck')).remaining,0);check('PM125-LUCK-ZERO-DISABLED',await p.locator('.adv-config-spend-luck').isDisabled());check('PM125-VISIBLE-UNLUCKY-REROLL',await p.locator('.unlucky-invoke').isVisible());await click(p,'.unlucky-invoke');check('PM125-UNLUCKY-REROLL',(await config(p,'Unlucky','disadv')).remaining,1);await closeRoll(p);await roll(p);check('PM125-VISIBLE-DP-REROLL',await p.locator('.dp4523-reroll').isVisible());await click(p,'.dp4523-reroll');await p.waitForSelector('#appConfirmOverlay',{state:'visible'});await click(p,'#appConfirmOk');await p.waitForTimeout(50);check('PM125-DARK-PARAGON-REROLL',(await config(p,'Dark Paragon')).remaining,0);check('PM125-REROLLS-NO-ERRORS',p.errors,[]);});
 await scenario('ENTRY-PATHS',async()=>{const p=await fresh(b);await seed(p,[F('Allies',{type:'dualTierPick',influence:1,devotion:2})]);await p.evaluate(()=>{const e=document.getElementById('f_name');e.value='Mode acceptance';e.dispatchEvent(new Event('input',{bubbles:true}));document.getElementById('btnSaveAs').click();});await p.waitForFunction(()=>!!document.getElementById('charSelect').value);const id=await p.locator('#charSelect').inputValue();await click(p,'#cl11Toolbar');await p.locator('.cl11-row[data-id="'+id+'"] .cl11-open').click();check('PM125-LIST-OPEN-LOCKS',await p.locator('#advList .en-name').evaluate(e=>e.readOnly));await click(p,'#cl11Toolbar');await p.locator('#cl11Create').click();await p.waitForFunction(()=>!document.getElementById('cw112View').hidden);await p.evaluate(()=>window.__L5R_TEST__.CW112.finish());await p.evaluate(()=>{const T=window.__L5R_TEST__,d=T.collectData();d.adv=[{name:'Allies',cost:3,desc:'',config:{type:'dualTierPick',influence:1,devotion:2}}];T.applyData(d);});await p.waitForTimeout(40);check('PM125-WIZARD-FINISH-LOCKS',await p.locator('#advList .en-name').evaluate(e=>e.readOnly));check('PM125-ENTRY-PATHS-NO-ERRORS',p.errors,[]);});
 }finally{for(const c of contexts)await c.close();await b.close();}console.log('\n'+passed+'/'+(passed+failed)+' checks passed');process.exitCode=failed?1:0;}
main().catch(e=>{console.error(e);process.exitCode=1;});
